### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by AmigaAbattoir** [BowlerHatLLC/eclipse-as3mxml#1]
Just wondering, do I need to build the extension or will you provide a built jar that can be dropped into Plugins/, or will there be a repo to add it to Eclipse?

**Comment by joshtynjala** [comment]
You need to build it, I guess. I think you create an Eclipse plugin project, or something, and then launch it. I don't really remember, and I'd need to look up the guides that I followed for using a language server in Eclipse.

To be clear, I have no plans to release this as a real supported plugin at this time. In particular, I found that opening a project and waiting for code intelligence took way too long (though it was fine once initialized). In my opinion, it's not really worth continuing work on this project, but I thought I'd share what I had. In fact, I'm going to "archive" this repo to avoid confusion.

I recommend using VSCode with the vscode-as3mxml extension, which is what this was based on.
